version: '3.3'
services:
  mongo:
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/mongodata
  api-one:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    environment:
      PORT: 8081
      MONGO_URI: ${MONGO_URI}
    ports:
      - 8081:8081
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
  api-two:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: ${ENVIRONMENT}
    environment:
      PORT: 8082
      MONGO_URI: ${MONGO_URI}
    ports:
      - 8082:8082
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo

  nginx:
    depends_on:
      - api-one
      - api-two
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
volumes:
  mongodata:
