version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: DockerFile
      target: ${ENVIRONMENT}
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - 4545:${PORT}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "8001:27017"
    volumes:
      - /data/db:/mongodata
volumes:
  mongodata:
