# Function to adjust MONGO_URI or assign default if empty
define adjust_mongo_uri
$(if $(or $(strip $(MONGO_URI)),abcd),\
$(if $(findstring mongodb://localhost:,$(MONGO_URI)),\
$(subst localhost,host.docker.internal,$(MONGO_URI)),\
$(MONGO_URI)),abcd)
endef

# Adjusted MONGO_URI
ADJUSTED_MONGO_URI:=$(strip $(call adjust_mongo_uri))



dev: build-api-dev run-api

prod: build-api-prod run-api

test: build-api-test run-api-test delete-container


build-api-dev:
	docker build -f DockerFile -t sre-api --target development .

build-api-prod:
	docker build -f DockerFile -t sre-api --target production .

build-api-test:
	docker build -f DockerFile -t sre-api --no-cache --target test .

run-api:
	docker run -d -v ./src:/usr/src/app/src -e PORT=$(PORT) -e MONGO_URI=$(ADJUSTED_MONGO_URI) --name sre-api -p $(PORT):$(PORT) sre-api

run-api-test:
	docker run -e PORT=$(PORT) -e MONGO_URI=$(ADJUSTED_MONGO_URI) --name sre-api -p $(PORT):$(PORT) sre-api

delete-container:
	docker stop sre-api
	docker rm sre-api
	docker rmi sre-api
