dev: create-network run-mongo build-api-dev run-api

prod: create-network run-mongo build-api-prod run-api

test: create-network run-mongo build-api-test run-api-test


build-api-dev:
	docker build -f DockerFile -t sre-api --target development .

build-api-prod:
	docker build -f DockerFile -t sre-api --target production .

build-api-test:
	docker build -f DockerFile -t sre-api --no-cache --target test .


create-network:
	docker network create SRE_NET

run-mongo:
	docker run -d --network SRE_NET --name mongo mongo

run-api:
	docker run -d -e PORT=$(PORT) -e MONGO_URI=mongodb://0.0.0.0:27017 --network SRE_NET --name sre-api -p $(PORT):$(PORT) sre-api

run-api-test:
	docker run -e PORT=$(PORT) -e MONGO_URI=mongodb://0.0.0.0:27017 --network SRE_NET --name sre-api -p $(PORT):$(PORT) sre-api

delete-container:
	docker stop sre-api mongo
	docker rm sre-api mongo
	docker network rm SRE_NET
	docker rmi sre-api
