name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and export to docker
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:test
      -
        name: test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          docker run --rm -e MONGO_URI=${{secrets.MONGO_URI}} ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:test
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest 